### ISSUE TITLE
Meeting Buchung

### ISSUE THREAD

**Issue by amenk** [markocupic/resource-booking-bundle#15]
Ist es denkbar, das Bundle zum Buchen von Meetings mit Personen (members) zu verwenden?
Welche Anpassungen wären nötig?

**Comment by markocupic** [comment]
Kommt halt auf den genauen **Verwendungszweck** an. Evtl. wäre auch [das ](https://github.com/markocupic/calendar-event-booking-bundle)was für dich. 
Du findest meine Mailadresse [hier](https://github.com/markocupic/calendar-event-booking-bundle/blob/514a76aa70d66464a5182f16e4c00b159b2c9b64/src/Resources/contao/classes/helpers/NotificationHelper.php#L5
).
Lg M
