### ISSUE TITLE
Installationsfehler per Composer

### ISSUE THREAD

**Issue by mpitz** [markocupic/resource-booking-bundle#17]
![image](https://user-images.githubusercontent.com/6831223/81481793-d0f5a100-9232-11ea-856e-44f05b5ad818.png)

Contao 4.9.2
PHP 7.3

**Comment by mpitz** [comment]
Anscheinend ist der Dateiname src/DependencyInjection/Compiler/AddSessionBagPass.php falsch. Da fehlt ein s nach Bag:

src/DependencyInjection/Compiler/AddSessionBagsPass.php

**Comment by markocupic** [comment]
Thanxxs! 
fixed in version 2.2.1

**Comment by mpitz** [comment]
Joa ... jetzt gibt es einen neuen Fehler:
![image](https://user-images.githubusercontent.com/6831223/81483127-0bb00700-923c-11ea-8c56-f68528f29bde.png)
