### ISSUE TITLE
Service 'session' Fehler bei der Installation per Composer

### ISSUE THREAD

**Issue by mpitz** [markocupic/resource-booking-bundle#18]
![image](https://user-images.githubusercontent.com/6831223/81483324-aa893300-923d-11ea-8700-424f6cba19f8.png)

Contao 4.9.2
PHP 7.3

**Comment by markocupic** [comment]
Ich kann den Fehler nicht nachvollziehen, merkwürdig. Bei mir läuft die Installation sauber durch, 
![Unbenannt](https://user-images.githubusercontent.com/1525166/81498655-7a39a700-92c6-11ea-8a62-7816b6374242.JPG)

**Comment by markocupic** [comment]
Any ideas?

**Comment by mpitz** [comment]
Ich habe auf einem weiteren Hosting versucht, mit dem gleichen Ergebnis.
Generell lässt sich das per Contao Manager installieren, aber eben nicht über die CLI per Composer.

**Comment by markocupic** [comment]
Ah... ok. Das ist ja immerhin schon einmal ein Anhaltspunkt. Erklärt aber noch nicht, woran es liegt. 

Ein `debug:container` auf der CLIi zeigt, dass der Service registriert ist. Weiss jetzt auch nicht wie weiter...
Hast du eine Idee?
![Unbenannt](https://user-images.githubusercontent.com/1525166/81553504-7c166f80-9385-11ea-85d5-7672b1c49b15.JPG)

**Comment by markocupic** [comment]
Fixed in 206a9a36599fd0a54180c409a12d2b8bb7fda8c4

Try version [2.2.5](https://github.com/markocupic/resource-booking-bundle/tree/2.2.5)
