### ISSUE TITLE
Rechteproblem

### ISSUE THREAD

**Issue by chriza** [markocupic/resource-booking-bundle#19]
Hallo,
ich habe in einer Installation ein Rechteproblem.

Ein Mitglied hat Mitgliedsgruppen X und Y.

Die Website hat u.a. folgende Seiten:

- Seite A (der Mitgliedsgruppe X zugewiesen) mit den Buchungsmodul M
- Seite B (der Mitgliedsgruppe Y zugewiesen) mit den Buchungsmodulen M und N

Für o.g. Mitglied wird die Seite B nicht angezeigt (Nicht genügend Rechte) und zur Root-Seite weitergeleitet. Wird auf der Seite B das Buchungsmodul M deaktiviert, wird die Seite dem o.g. Mitglied angezeigt.

**Comment by markocupic** [comment]
Das heisst, dass du auf der selben Seite 2 Buchungsmodule einsetzen willst?

**Comment by markocupic** [comment]
Ok! Try branch [2.4.0-dev](https://github.com/markocupic/resource-booking-bundle/tree/2.4.0-dev)

![Unbenannt](https://user-images.githubusercontent.com/1525166/83975816-2e464600-a8f6-11ea-9d83-fa90163f13f6.JPG)
