### ISSUE TITLE
Feature Request: Username statt vollem Namen im Template

### ISSUE THREAD

**Issue by Kahmoon** [markocupic/resource-booking-bundle#20]
Hi,

ich teste gerade deine Erweiterung und bin begeistert. Ich habe aber ein kleines Problem das im Template der Vor- und Nachname des Mitglieds via "bookedByFullname" ausgegeben wird. Aus Datenschutzgründen bräuchte ich aber den Usernamen.

So wie ich das sehe wird dieser derzeit in der Buchung nicht gespeichert!? Oder gibt es eine Variable die ich übersehen habe?

VG Frank

**Comment by markocupic** [comment]
Umgesetzt in 4ff31518be2d01f3747d56f83f83b20e40c6f806
Mache ein Update  auf Version 2.5.0
Installtool laufen lassen.
Danach kannst du in den Moduleinstellungen (tl_module) einstellen, welche Felder übermittelt werden sollen. Falls der eingeloggte Benutzer auch derjenige ist, der das Feld gebucht hat, sieht er alles. Von fremden Usern sieht man nur, das, was in tl_module eingestellt wurde.
Im Template erreichst du die Daten dann in Zeile 102 über: eventBox.bookedByFullname oder eventBox.bookedByUsername, etc.

**Comment by Kahmoon** [comment]
Wow...sehr schnelle Umsetzung. Danke! :-)
