### ISSUE TITLE
Feature Request: Nur Datum in der Vergangenheit einstellbar (Dropdown)

### ISSUE THREAD

**Issue by Kahmoon** [markocupic/resource-booking-bundle#21]
Guten Morgen,

jetzt komme ich gleich noch mit einem weiteren Wunsch ums Eck :-). In unserem Fall (Belegungsplan für Jagd-Hochsitze) ist die Anzeige in der Vergangenheit irrelevant. Im Core Kalendermodul Liste kann man es einstellen ob Datum in der Vergangenheit angezeigt wird oder nicht. Man kann in der Vergangenheit ja ohnehin keine Termine buchen.

Ich meine hier speziell das Dropdown bei der Ressourcenauswahl. 

VG Frank

**Comment by markocupic** [comment]
Via localconfig.php solltest du diesen Parameter überschreiben können. 
https://github.com/markocupic/resource-booking-bundle/blob/a606b578ebc7aa2cc9bc1097aac9dac3abdb90a9/src/Resources/contao/config/config.php#L30
Danach cache neu aufbauen

**Comment by Kahmoon** [comment]
localconfig.php gibts ja in 4.9 nicht mehr so wirklich. Sprich es müsste in der neuen Struktur eher eine Datei in contao/dca sein oder?

**Comment by Kahmoon** [comment]
Jepp, in der Datei contao/config/config.php funktioniert es. Danke

**Comment by markocupic** [comment]
Ja, genau.
