### ISSUE TITLE
Modul beisst sich mit bestehender Fontawesome integration

### ISSUE THREAD

**Issue by Kahmoon** [markocupic/resource-booking-bundle#22]
Wenn ich ein Buchungsmodul auf einer Seite platziere, gehen im Anschluss die vorhandenen Font Awesome Elemente nicht mehr.

Siehe Navigation links https://ibb.co/YQNw6gt

Font Awesome ist bei uns lokal via externes CSS im Layout eingebunden.

VG

**Comment by markocupic** [comment]
Dju kannst das Template anzupassen oder nicht?

**Comment by Kahmoon** [comment]
Ich bin doof....habe nicht gesehen das FA über das Template eingebunden wird. Sorry!
