### ISSUE TITLE
Enhancement: Verbesserung der Logeinträge

### ISSUE THREAD

**Issue by Kahmoon** [markocupic/resource-booking-bundle#23]
Guten Morgen,

in unserem Fall habe ich 4 Einzelne Ressourcen (Hochsitz A, Hochsitz B etc.) angelegt. Wenn sich jetzt jemand dort etwas bucht steht im Log nur "New resource with ID 131 has been booked.". 

Für mich als Admin wäre es viel übersichtlicher wenn in diesem Eintrag auch der Name der Ressource stehen würde. Aktuell müsste ich alle einzeln durchsuchen.

z.B. New entry with ID 131 has been booked in **MeinHochsitz**

Also quasi in der Datei: resource-booking-bundle/src/Ajax/AjaxHandler.php Zeile 281

`$strLog = sprintf('New entry with ID %s has been booked in '.$objResource->title.'.', $objBooking->id);`

oder noch besser mit Username.

`$strLog = sprintf('New resource with ID %s has been booked in '.$objResource->title.' by  '.$this->objUser->username.'.', $objBooking->id);`

Gleiches beim Löschvorgang Zeile 432 (Dort ist die Variable für den Title leider nicht verfügbar)
`$strLog = sprintf('Resource Booking with ID %s in '.$objResource->title.' has been deleted.', $intId);`

bzw.

`$strLog = sprintf('Resource Booking with ID %s has been deleted by '.$this->objUser->username.'.', $intId);`

VG

**Comment by markocupic** [comment]
Du könntest dir auch via Hook bei einer Buchung eine Benachrichtigung senden lassen.

**Comment by Kahmoon** [comment]
Nah, das wäre übertrieben. Ich würde nur gerne im Log sehen was da gebucht wurde ohne mit viel Klicks zu recherchieren.

**Comment by Kahmoon** [comment]
Servus,

habe gesehen das es ein Update gab. Dort sind aber Änderungsvorschläge von diesem Issue nicht drin oder? Soweit ich das sehen kann wurden im Template nur "static" Befehle entfernt.

Frage nur sicherheitshalber weil ich mir beim Update sonst die Log Anpassungen überschreibe.

VG

**Comment by markocupic** [comment]
Jepp... Bin noch nicht dazu gekommen.

**Comment by Kahmoon** [comment]
Kein Ding. Wollte nur sicher gehen :)

**Comment by markocupic** [comment]
Added in 1b094316b633924c202a12e5f04ddc3b617ab700

**Comment by Kahmoon** [comment]
Danke für die Umsetzung. 

Wie bekomme ich denn da jetzt noch den Usernamen ins log (updatesicher)?

**Comment by markocupic** [comment]
Hmmm. Pull request😛

**Comment by Kahmoon** [comment]
Hatte ich das nicht hier schon in diesem gemacht? :-P

**Comment by Kahmoon** [comment]
Darf ich hier noch mal nachhaken? Ich muss nach jedem Update meine Änderungen von Hand nachziehen. Diese Ergänzungen im Log wären aber glaub ich für alle hilfreich.

Einen Pull Request kann ich nicht öffnen ;-)

**Comment by markocupic** [comment]
Ja... verstehe ich. Da es sich um eine freie Erweiterung handelt, für die ich keinen Cent/Rappen kriege, musst du damit leben können. Sorry.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.

**Comment by Kahmoon** [comment]
Ja, das verstehe ich. Aber diese "kleine" Änderung wurde halt der ganzen Erweiterung helfen. 

Und wir sind die letzten die nicht mal eine Anpassung von Modulen kostenpflichtig beauftragen.

**Comment by markocupic** [comment]
Hallo FrankDu darfst dich gerne bei mir per E-Mail melden. Du findest die Kontaktdaten im Code.LG marko --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 22.10.20, 11:10 schrieb Frank <notifications@github.com>:

   
  Ja, das verstehe ich. Aber diese "kleine" Änderung wurde halt der ganzen Erweiterung helfen. 
  Und wir sind die letzten die nicht mal eine Anpassung von Modulen kostenpflichtig beauftragen.
