### ISSUE TITLE
Contao 4.10.3 keine Frontendmodule mehr

### ISSUE THREAD

**Issue by Kahmoon** [markocupic/resource-booking-bundle#24]
Servus,

ich habe gerade eine Installation auf Contao 4.10.3 gehoben und alle Booking Module sind jetzt nicht mehr verfügbar :-(. Im Frontend wird somit keine Buchungsmaske mehr geladen.

Ein bestehendes Modul ist jetzt Typ "unbekannte Option". Alle Einstellungen aus dem Modul werden allerdings angezeigt!? In der Liste aller Modultypen ist die Buchung nicht mehr vorhanden.

Es handelt sich hier leider um ein Livesystem, da ich den Fehler vorher im Dev nicht bemerkt habe :(

<a href="https://ibb.co/G7GK8wY"><img src="https://i.ibb.co/9nBF1XK/Bildschirmfoto-2020-10-07-um-14-08-42.png" alt="Bildschirmfoto-2020-10-07-um-14-08-42" border="0"></a>

In der Modulübersicht steht es noch korrekt.
<a href="https://ibb.co/sKb0c0z"><img src="https://i.ibb.co/QPp2h2t/Bildschirmfoto-2020-10-07-um-15-00-42.png" alt="Bildschirmfoto-2020-10-07-um-15-00-42" border="0"></a>

Contao:4.10.3
Modul: 2.5.2 

VG

**Comment by fritzmg** [comment]
https://github.com/contao/contao/issues/2415

**Comment by markocupic** [comment]
Added conflict contao/core 4.10.3 in 702412d7eb98c1530d2c186534225369a1ff6eac
