### ISSUE TITLE
Resource Vorauswahl weg seit Version 2.6.0

### ISSUE THREAD

**Issue by Kahmoon** [markocupic/resource-booking-bundle#25]
Servus,

seit dem letzten Update des Moduls muss ich immer noch eine Resource manuell auswählen obwohl es nur eine gibt. Das ist von der usability her bissl nervig. Bisher war das nicht so.

Aktuell habe ich pro Booking nur eine Resource. Das hat den Hintergrund das im Bereich Hochsitz X nicht versehentlich Hochsitz Y gewählt werden kann.

Könnte man das wieder umstellen das es direkt die **einzige Option** auswählt wenn es nur eine **einzige** gibt? Das wäre super :-)

<a href="https://ibb.co/5cLsFrr"><img src="https://i.ibb.co/4Np4d88/Bildschirmfoto-2020-10-20-um-12-21-22.png" alt="Bildschirmfoto-2020-10-20-um-12-21-22" border="0"></a>
<a href="https://ibb.co/Xb5Z7Zf"><img src="https://i.ibb.co/f2NYkYV/Bildschirmfoto-2020-10-20-um-12-19-02.png" alt="Bildschirmfoto-2020-10-20-um-12-19-02" border="0"></a>

VG

**Comment by markocupic** [comment]
Ohne Gewähr ;-)
Fixed in 7cc93a62fc7cc8155fc81a6219f49d596a44b2de

**Comment by Kahmoon** [comment]
Danke. Teste ich morgen direkt mal

**Comment by Kahmoon** [comment]
Funktioniert super. Danke!!!1
