### ISSUE TITLE
Feature: Benachrichtigungen

### ISSUE THREAD

**Issue by mecintosch** [markocupic/resource-booking-bundle#27]
Eine Nachricht an den Admin bei neuer Buchung bzw. Stornierung wäre ein tolles Feature.

Eventuell umgesetzt mit dem Notification Center wie bei calendar-event-booking-bundle.

**Comment by markocupic** [comment]
@mecintosch 
Gerne kannst du dich per E-Mail bei mir melden und die Weiterentwicklung der Extension mit einem Kleinauftrag unterstützen.
E-Mailadresse findest du im Code.
Lg Marko

**Comment by markocupic** [comment]
https://github.com/markocupic/resource-booking-bundle#benachrichtigung
