### ISSUE TITLE
rbb 3.0.13 läuft nicht unter contao 4.12.1

### ISSUE THREAD

**Issue by jaennert** [markocupic/resource-booking-bundle#29]
Beim Update von contao auf 4.12.1 und rbb auf 3.0.13 habe ich folgende Fehlermeldung:
…
Class League\Uri\Schemes\Ws located in ./vendor/league/uri-schemes/src/Schemes/deprecated.php does not comply with psr-4 autoloading standard. Skipping.
87 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

In ScriptHandler.php line 95:
                                                                           
  An error occurred while executing the "contao:install-web-dir" command:  
                                                                           

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [...]

# Process terminated with exit code 1
# Result: General error

fritzmg schreibt unter Slack:
Und der Fehler hat nichts mit Contao 4.12 zu tun. markocupic/resource-booking-bundle verwendet hier PHP 8 features - dies wurde aber in der composer.json des Pakets nicht berücksichtigt. (bearbeitet)

**Comment by markocupic** [comment]
Kann man das issue schließen?

**Comment by jaennert** [comment]
Hinweis ein issues anzulegen kam von fritzmg

**Comment by markocupic** [comment]
Ja, habe es gelesen in slack :-)LG marko --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 30.08.21, 21:54 schrieb jaennert ***@***.***>:

   
  Hinweis ein issues anzulegen kam von fritzmg
